name: Test
on: [push, pull_request]

jobs:
  test_ima_js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MANAGER_TAG: "1.8.1-develop.6"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Install dependencies
      run: |
        yarn install --production=false
    - name: Lint code
      run: |
        yarn global add tslint typescript
        yarn lint
    - name: Run ima-sdk
      run: |
        bash scripts/run_ima_sdk.sh
    - name: Wait for contracts
      run: |
        bash scripts/wait_for_contracts.sh
    