name: Test
on: [push, pull_request]

jobs:
  test_ima_js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    env:
      PRIVATE_KEY_FOR_ETHEREUM: ${{ secrets.PRIVATE_KEY_FOR_ETHEREUM }}
      ACCOUNT_FOR_ETHEREUM: ${{ secrets.ACCOUNT_FOR_ETHEREUM }}
      ACCOUNT_FOR_SCHAIN: ${{ secrets.ACCOUNT_FOR_SCHAIN }}
      PRIVATE_KEY_FOR_SCHAIN: ${{ secrets.PRIVATE_KEY_FOR_SCHAIN }}

      MAINNET_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_FOR_ETHEREUM }}
      MAINNET_ADDRESS: ${{ secrets.ACCOUNT_FOR_ETHEREUM }}
      MAINNET_ENDPOINT: http://127.0.0.1:8545

      SCHAIN_ADDRESS: ${{ secrets.ACCOUNT_FOR_SCHAIN }}
      SCHAIN_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_FOR_SCHAIN }}
      SCHAIN_ENDPOINT: http://127.0.0.1:15000
      CHAIN_NAME_SCHAIN: "Bob"
      INSTALL_PACKAGES: "True"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Install dependencies
      run: |
        yarn install --production=false
    - name: Lint code
      run: |
        yarn global add tslint typescript
        yarn lint
    - name: Run ima-sdk
      run: |
        bash scripts/run_ima_sdk.sh
    - name: Wait for contracts
      run: |
        bash scripts/wait_for_contracts.sh
    - name: Deploy test tokens
      run: |
        sudo -E yarn deploy-tokens
    - name: Run tests
      run: |
        sudo -E yarn test
