name: Test
on: [push, pull_request]

jobs:
  test_ima_js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    env:
      PRIVATE_KEY_FOR_ETHEREUM: ${{ secrets.PRIVATE_KEY_FOR_ETHEREUM }}
      ACCOUNT_FOR_ETHEREUM: ${{ secrets.ACCOUNT_FOR_ETHEREUM }}
      ACCOUNT_FOR_SCHAIN: ${{ secrets.ACCOUNT_FOR_SCHAIN }}
      PRIVATE_KEY_FOR_SCHAIN: ${{ secrets.PRIVATE_KEY_FOR_SCHAIN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Install dependencies
      run: |
        yarn install --production=false
    - name: Lint code
      run: |
        yarn global add tslint typescript
        yarn lint
    - name: Run ima-sdk
      run: |
        bash scripts/run_ima_sdk.sh
    - name: Wait for contracts
      run: |
        bash scripts/wait_for_contracts.sh
    