name: Test
on: [push, pull_request]

jobs:
  test_manager:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MANAGER_TAG: "1.8.1-develop.6"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        yarn install
    - name: Lint code
      run: |
        yarn lint